project:
  type: website

website:
  title: "Webinaire Arrow"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - href: representation_donnees.qmd
        text: Représentation des données
      - href: immutabilite.qmd
        text: Immutabilité dans R
    search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
