project:
  type: website

website:
  title: "webinaire_arrow"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - href: format_r.qmd
        text: Formats R vs arrow
    search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


